### ISSUE TITLE
CASE does not support assignment to local variables

### ISSUE THREAD

**Issue by azaky** [fushar/tcframe#31]
The following code will receive a compilation error: `error: i is not captured`.

    for (int i = 1; i <= 10; ++i) {
        CASE(N = 10, K = i);
    }

The cause is (most likely) that because `i` is a local variable, and CASE is using lambda expression. When this expression is executed, `i` is not defined there.

A little hack can do the trick, but it is not so pretty. It will be nice if tcframe support assignment to local variables.

    for (int i = 1; i <= 10; ++i) {
        this->_N = 10;
        this->_K = i;
        CASE(assignValues());
    }

where `_N` and `_K` are private variables, and the `assignValues()` is defined as follows.

    void assignValues() {
        N = _N;
        K = _K;
    }

**Comment by azaky** [comment]
**EDIT**: the above workaround does not work. It is only compile-error free, but will generate wrong outputs.

**Comment by jonathanirvings** [comment]
I believe the workaround above will all produce the case where K = 10.
@raisfathin found a working hack.
```
this->_K = 0;
for (int i = 1; i <= 10; ++i) {
    CASE(N = 10; K = ++this->_K);
}
```
But still, it will be good if tcframe support assignment to local variables.

**Comment by fushar** [comment]
It is now supported, folks! :)
